version: '3.8'
services:
  jenkins:
    build:
      context: .
    image: jenkins-docker-client
    container_name: jenkins
    restart: always
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2376 
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - net
    depends_on:
      - docker
  
  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      - net

networks:
  net:

volumes:
  jenkins-data:
  jenkins-docker-certs: